image: node:latest

pages:
  script:
    - mkdir .public
    - cp index.html .public
  artifacts:
    paths:
      - .public
  only:
    - main  # замените 'main' на имя вашей ветки, если это необходимо
